apiVersion: apps/v1
kind: Deployment
metadata:
  name: memory-validating-webhook-deployment
  labels:
    app: memory-validating-webhook
spec:
  replicas: 1
  selector:
    matchLabels:
      app: memory-validating-webhook
  template:
    metadata:
      labels:
        app: memory-validating-webhook
    spec:
      serviceAccountName: memory-validating-webhook-sa
      containers:
        - name: memory-validating-webhook
          image: kimoqi/memory-validating-webhook:v1
          imagePullPolicy: Always
          args:
            - -tlsCertFile=/etc/webhook/certs/cert.pem
            - -tlsKeyFile=/etc/webhook/certs/key.pem
            - -alsologtostderr
            - -v=4
            - 2>&1
          volumeMounts:
            - name: webhook-certs
              mountPath: /etc/webhook/certs
              readOnly: true
      volumes:
        - name: webhook-certs
          secret:
            secretName: memory-validating-webhook-certs