apiVersion: v1
kind: ServiceAccount
metadata:
  name: memory-validating-webhook-sa
  labels:
    app: memory-validating-webhook

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: memory-validating-webhook-cr
  labels:
    app: memory-validating-webhook
rules:
  - apiGroups:
      - qikqiak.com
    resources:
      - "*"
    verbs:
      - "*"
  - apiGroups:
      - ""
    resources:
      - pods
      - events
    verbs:
      - "*"
  - apiGroups:
      - apps
    resources:
      - deployments
      - daemonsets
      - replicasets
      - statefulsets
    verbs:
      - "*"
  - apiGroups:
      - autoscaling
    resources:
      - '*'
    verbs:
      - '*'

---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: memory-validating-webhook-crb
  labels:
    app: memory-validating-webhook
subjects:
  - kind: ServiceAccount
    name: memory-validating-webhook-sa
    namespace: default
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: memory-validating-webhook-cr