apiVersion: v1
kind: Service
metadata:
  name: memory-validating-webhook-svc
  labels:
    app: memory-validating-webhook
spec:
  ports:
    - port: 443
      targetPort: 443
  selector:
    app: memory-validating-webhook