apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: memory-validating-webhook
  labels:
    app: memory-validating-webhook
webhooks:
  - name: my-webhook.example.com
    clientConfig:
      service:
        name: memory-validating-webhook-svc
        namespace: default
        path: "/validate"
      caBundle: ${CA_BUNDLE}
    rules:
      - operations: [ "CREATE" ]
        apiGroups: ["apps", ""]
        apiVersions: ["v1"]
        resources: ["deployments","services","pods"]
    namespaceSelector:
      matchLabels:
        memory-validating-webhook: enabled
    admissionReviewVersions: ["v1","v1beta1"]
    sideEffects: None
    objectSelector:
      matchExpressions:
        - key: app
          operator: NotIn
          values:
            - "memory-validating-webhook"